name: bottom
description: Dart library for translating between bottom and human-readable text.
version: 2.0.0
homepage: https://github.com/oliver-ni/bottom-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
